<a href="https://colab.research.google.com/github/ayamlearning/machine-learning-zoomcamp/blob/main/Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
from google.colab import drive
drive.mount('/content/drive')
path='/content/drive/MyDrive/ML-Zoomcamp/Exercises/Ex1/Data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Question 1

In [93]:
import pandas as pd
import numpy as np
pd.__version__

'1.5.3'

In [94]:
df=pd.read_csv(path+'/housing.csv')
df.sample(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1999     -119.77     36.74                20.0       1855.0           519.0   
9078     -118.14     34.69                48.0       1379.0           327.0   
1498     -122.01     37.93                25.0       2652.0           335.0   
15283    -117.33     33.17                11.0      10923.0          2041.0   
4463     -118.18     34.08                35.0       2226.0           602.0   

       population  households  median_income  median_house_value  \
1999       1091.0       443.0         1.5547             93900.0   
9078        696.0       304.0         2.1167             94900.0   
1498       1062.0       334.0         7.5898            330200.0   
15283      4773.0      1858.0         4.0791            281300.0   
4463       2230.0       549.0         2.9167            129300.0   

      ocean_proximity  
1999           INLAND  
9078           INLAND  
1498         NEAR BAY  
15283      NEAR OCEAN  
4463        <1H OCEAN

## Question 2

In [95]:
df.shape

(20640, 10)

## Question 3

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 4

In [97]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

## Question 5

In [98]:
df_near_bay = df.loc[df['ocean_proximity'] == 'NEAR BAY']
round(df_near_bay['median_house_value'].mean(),0)

259212.0

## Question 6

In [99]:
round(df['total_bedrooms'].mean(),3)

537.871

In [100]:
#Calculate the average of total_bedrooms column in the dataset.
mean_value = round(df['total_bedrooms'].mean(),0)
#Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
df['total_bedrooms'].fillna(value=mean_value, inplace=True)
#Now, calculate the average of total_bedrooms again.
round(df['total_bedrooms'].mean(),3)

537.872

## Question 7


In [101]:
#Select all the options located on islands.
df_island = df.loc[df['ocean_proximity'] == 'ISLAND']

#Select only columns housing_median_age, total_rooms, total_bedrooms.
df_island = df_island[['housing_median_age','total_rooms','total_bedrooms']]
df_island

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [102]:
#Get the underlying NumPy array. Let's call it X.
X= df_island.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [103]:
#Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
X_trans = X.T
XTX = X_trans.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [104]:
#Compute the inverse of XTX
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [105]:
#Create an array y with values [950, 1300, 800, 1000, 1300].
y= np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [106]:
#Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w
XTXinvXT = XTXinv.dot(X_trans)
w = XTXinvXT.dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])